"""empty message

Revision ID: 32b02efb287d
Revises: 
Create Date: 2020-04-21 12:59:20.868267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32b02efb287d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    category_table = op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    default_categories = [
        {'id': 1, 'type': 'Science'},
        {'id': 2, 'type': 'Art'},
        {'id': 3, 'type': 'Geography'},
        {'id': 4, 'type': 'History'},
        {'id': 5, 'type': 'Entertainment'},
        {'id': 6, 'type': 'Sports'}
    ]
    op.bulk_insert(category_table, default_categories)

    question_table = op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    default_questions = [
        {'id': 1, 'question': 'What year was John Lennon born?', 'answer': '1940', 'category': '5', 'difficulty': 4},
        {'id': 2, 'question': 'Which scientist developed the theory of relativity?', 'answer': 'Albert Einstein', 'category': '1', 'difficulty': 2}
    ]
    op.bulk_insert(question_table, default_questions)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    op.drop_table('categories')
    # ### end Alembic commands ###
